name: CI/CD

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev_web' }}
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Après merge on veut le code final de main
          ref: main
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: website/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint -- --max-warnings=0
      - name: Run tests
        run: npm test -- --ci --coverage
      - name: Build static export
        run: npm run build
      - name: Upload static site artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: website/out
          if-no-files-found: error

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev_web' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site
          path: out

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "out/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}/current



