name: Deploy Production

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Remote deploy (git pull + docker compose)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 2222
          script: |
            cd ${{ secrets.DEPLOY_REPO_PATH }}
            git pull
            cd website
            docker compose down
            docker compose up -d --build
          
